-- Create judges table for tournament judge registrations
create table if not exists public.judges (
  id bigint generated by default as identity primary key,
  tournament_id integer not null references public.tournaments(id) on delete cascade,
  judge_username text not null,
  club text,
  status text not null default 'pending',
  timestamp timestamptz not null default now(),
  constraint judges_unique_per_tournament unique (tournament_id, judge_username)
);

-- Helpful index for lookups
create index if not exists idx_judges_tournament on public.judges(tournament_id);


